### PR TITLE
Feature/qnap

### PR DESCRIPTION
**Pull request by RazeemM**

### CODE REVIEW

**Review by Raphyyyy — DISMISSED** [review]
Looks good for QNAP ;) ! No comment ;D !

**Comment by bertysentry** [comment]
**QNAP/README.md** is empty. You need to put some description there.

**Comment by bertysentry** [comment]
Also, changed files include stuff about EMC Isilon. Is it because you branched from another *feature* branch?

**Review by bertysentry — CHANGES_REQUESTED** [review]
Please add README.md for QNAP

**Review by bertysentry — APPROVED** [review]

**Review by Raphyyyy — APPROVED** [review]

**Review by alexdgilbert — APPROVED** [review]
Looks good to me!

**Pull request merged**
