### PR TITLE
Monitoring Informix DB through SNMP

### PR DESCRIPTION
**Pull request by RazeemM**

### CODE REVIEW

**Comment by Raphyyyy** [comment]
Looks good except for Dynamic Instance Display Name, I think you should avoid to compute the "Index" OID because it's empty most of the time (Application details, Chunks, Logical log, Online DB space, online session and table Metrics). But maybe it's our system which doesn't work well so I will validate but feel free to "fix" it 

image

**Review by Raphyyyy — DISMISSED** [review]

**Comment by bertysentry** [comment]
Zipped MIBs should be removed from the repository, right?

**Comment by bertysentry** [comment]
@RazeemM Did you see @Raphyyyy 's comment?

**Comment by RazeemM** [comment]
> 
> 
> Zipped MIBs should be removed from the repository, right?

I wanted them to be there for the users to add additional parameters if required

**Comment by RazeemM** [comment]
> 
> 
> @RazeemM Did you see @Raphyyyy 's comment?

Only the log files are not returning the Index column. Could be something to do with the docker container we use. I discussed it with @Raphyyyy  and we decided to leave it that way.

**Comment by bertysentry** [comment]
Rescale some of the values to be more reasonable:
* BAR Activity / Elapsed Time (s) -> minutes
* Active Servers / Resident Memory Size (Kb) -> MB
* Active Servers / Virtual Memory Size (Kb) -> MB
* etc.

**Comment by bertysentry** [comment]
Change "total" values to display the Delta/sec or /min or /hour:
* Open Tables / Lock Requests -> Delta/min
* Open Tables / Lock Waits -> Delta/min
* Open Tables / Total ISAM * (the 3 of them) -> Delta/min

**Comment by bertysentry** [comment]
Open Tables / Status: "Dirty" is not a problem and it should not trigger a warning (Suspicious)

**Comment by bertysentry** [comment]
Applications > Operational Status: please use title case for "Status Information" in the value map

**Comment by bertysentry** [comment]
Chunks: Use Delta/s for Page Reads, Page Writes, Page Allocated, Reads and Writes. I'm not sure about Pages Used.

**Comment by bertysentry** [comment]
Chunks > Mirror Status and Status have exactly the same Value Map, is this normal?

**Comment by bertysentry** [comment]
Replication Sites > Activity State: use title case in Status Information field

**Comment by bertysentry** [comment]
Replication Sites, use Delta/min for all applicable metrics

**Comment by bertysentry** [comment]
Fragment: Use Delta/min where applicable

**Comment by bertysentry** [comment]
Active Sessions:
* Current Memory Usage Kb -> MB
* ISAM Read Calls -> Delta/min
* ISAM Writes -> Delta/min
* Lock Requests -> Delta/min
* Lock Timeouts -> Delta/min
* Lock Waits -> Delta/min
* Log Space Used Bytes -> MB
* Long Transactions -> Delta/min
* Page Reads -> Delta/min
* Page Writes-> Delta/min

**Comment by bertysentry** [comment]
Physical Log / Log Files:
* Buffer Size -> MB (what is the unit here?)
* Buffer Used -> MB (ideally, we would have a percentage... :-/ )
* Log Writes -> Delta/min
* Page Writes -> Delta/min

**Comment by bertysentry** [comment]
Remove the DB Query `SELECT * FROM sysdatabases`, I suppose it's not supposed to be here, is it?

**Review by bertysentry — CHANGES_REQUESTED** [review]
Some changes required, please :-)

**Comment by RazeemM** [comment]
> 
> 
> Rescale some of the values to be more reasonable:
> 
>     * BAR Activity / Elapsed Time (s) -> minutes
> 
>     * Active Servers / Resident Memory Size (Kb) -> MB
> 
>     * Active Servers / Virtual Memory Size (Kb) -> MB
> 
>     * etc.

Changes implemented.

**Comment by RazeemM** [comment]
> 
> 
> Open Tables / Status: "Dirty" is not a problem and it should not trigger a warning (Suspicious)

Changed to OK.

**Comment by RazeemM** [comment]
> 
> 
> Chunks > Mirror Status and Status have exactly the same Value Map, is this normal?

Yes. As per the MIB definition.

**Comment by RazeemM** [comment]
> 
> 
> Chunks: Use Delta/s for Page Reads, Page Writes, Page Allocated, Reads and Writes. I'm not sure about Pages Used.

Pages Used is the current value for that chunk.

**Comment by RazeemM** [comment]
> 
> 
> Remove the DB Query `SELECT * FROM sysdatabases`, I suppose it's not supposed to be here, is it?

Wanted to have an example. Removed.

**Comment by RazeemM** [comment]
> 
> 
> Physical Log / Log Files:
> 
>     * Buffer Size -> MB (what is the unit here?)
> 
>     * Buffer Used -> MB (ideally, we would have a percentage... :-/ )
> 
>     * Log Writes -> Delta/min
> 
>     * Page Writes -> Delta/min

Buffer used and size are measured in "Pages".

**Comment by RazeemM** [comment]
> 
> 
> Active Sessions:
> 
>     * Current Memory Usage Kb -> MB
> 
>     * ISAM Read Calls -> Delta/min
> 
>     * ISAM Writes -> Delta/min
> 
>     * Lock Requests -> Delta/min
> 
>     * Lock Timeouts -> Delta/min
> 
>     * Lock Waits -> Delta/min
> 
>     * Log Space Used Bytes -> MB
> 
>     * Long Transactions -> Delta/min
> 
>     * Page Reads -> Delta/min
> 
>     * Page Writes-> Delta/min

Changes implemented.

**Comment by RazeemM** [comment]
> 
> 
> Fragment: Use Delta/min where applicable

Done.

**Comment by RazeemM** [comment]
> 
> 
> Replication Sites, use Delta/min for all applicable metrics

Done.

**Comment by RazeemM** [comment]
Changes Implemented.

**Review by bertysentry — CHANGES_REQUESTED** [review]
A few more changes required:
* Remove "IFX User" credentials in Template
* Indicate in the label when it's /min (Log Writes/min for example), or in MB
* ElapsedTimeInMinute: I don't understand why it's divided by 6000 (should be 60, I suppose)
Thank you!

**Comment by RazeemM** [comment]
> 
> 
> A few more changes required:
> 
>     * Remove "IFX User" credentials in Template
> 
>     * Indicate in the label when it's /min (Log Writes/min for example), or in MB
> 
>     * ElapsedTimeInMinute: I don't understand why it's divided by 6000 (should be 60, I suppose)
>       Thank you!

Divided by 6000 as the value is in timeticks.

Other changes done.

**Review by bertysentry — APPROVED** [review]
Excellent!

**Pull request merged**
