### PR TITLE
Dell EMC Isilon OneFS REST API

### PR DESCRIPTION
**Pull request by RazeemM**

### CODE REVIEW

**Comment by MohammedSentry** [comment]
@RazeemM I think there is a conversion issue for the Used HDD Capacity of the StoragePool
image

**Comment by MohammedSentry** [comment]
@RazeemM can you display the Storagepool values in GB instead of MB ?

**Comment by RazeemM** [comment]
> 
> 
> @RazeemM can you display the Storagepool values in GB instead of MB ?

@MohammedSentry Units modified to GB.

**Comment by MohammedSentry** [comment]
@RazeemM no more USED HDD CAPACITY ?

**Review by bertysentry — APPROVED** [review]
Good to me. Please check @MohammedSentry 's question. Thanks!

**Comment by bertysentry** [comment]
@RazeemM no more USED HDD CAPACITY?

**Comment by RazeemM** [comment]
> 
> 
> @RazeemM no more USED HDD CAPACITY?

It is there.
image

**Comment by RazeemM** [comment]
> 
> 
> @RazeemM no more USED HDD CAPACITY ?
> 
> image

There was no Used HDD Capacity for Nodepool. It is there for Storagepool.

**Pull request merged**
