### PR TITLE
Creation of Microsoft Project Server template, compatible with versio…

### PR DESCRIPTION
**Pull request by alexdgilbert**
…ns 2013,2016 and 2019. Readme has also been created and contains instructions on the minute changes required between versions.

### CODE REVIEW

**Comment by Raphyyyy** [comment]
Maybe add a description in the template ?

**Review by bertysentry — COMMENTED** [review]
Performance Counters (General) do not collect on @RazeemM 's test system

**Comment by bertysentry** [comment]
Add reasonable alert thresholds to Performance Counters (do Microsoft have recommendations?)

**Comment by bertysentry** [comment]
Performance Counters (Queue Jobs and Winproj) do not collect on @RazeemM 's test system

**Comment by bertysentry** [comment]
Again, on @RazeemM 's test system, the cmdlets are really slow. It takes 20 to 50 seconds to execute each of them. That's weird. Is this expected? If so, we need to change the default alert thresholds on the ExecutionTime parameter.

**Comment by bertysentry** [comment]
Isn't there a way for the cmdlets to output in JSON or XML? It would be easier to parse.

**Comment by bertysentry** [comment]
Change template name from **ProjectServer** to **Project Server**

**Comment by RazeemM** [comment]
@bertysentry It's Alex's system. Not mine

**Comment by bertysentry** [comment]
Rename the embedded files so they don't say "Test" (or was it intentional?)
* `%{FILE:TestProjectServiceApp.ps1}`
* `%{FILE:TestProjectWebInstance.ps1}`

**Comment by bertysentry** [comment]
Event monitoring is not working on @RazeemM 's test system. How is that even possible?

**Comment by bertysentry** [comment]
Embedded file `%{FILE:License.ps1}` doesn't seem to be used.

**Comment by bertysentry** [comment]
In Dynamic Instances **projectserver:powershellCmdlets:projectServiceApp:getServiceAppInstances:serviceAppInstance** in the Separators option, adjacent separators must be kept (and not squashed)

**Comment by bertysentry** [comment]
Okay, @RazeemM just informed me it's now **his** test system, but @alexdgilbert 's test system ;-)

**Review by bertysentry — CHANGES_REQUESTED** [review]
Some changes required, but it's a good start :-)

**Comment by alexdgilbert** [comment]
@bertysentry 
Most of these changes are simple enough. A few thoughts for those below:

- The performance counters specific to Project Server are those recommended by Microsoft, however, the recommended thresholds are not documented, as such I'll use personal judgement for those. However, even on my test environment, they will not be reporting anything, simply because to create a project and have the jobs and queues kick into motion, you need to use the Microsoft Project client, which Microsoft does not seem too keen to provide a trial license.

- The names for the embedded files are named as such because the PS1 command having that syntax. I could rename them HealthCheckProjectServiceApp.ps1 or something similar.

- The time taken for the cmdlets seems to unfortunately be on the host side, and as such will not be shortened significantly if we use a JSON or XML file. (Just tested, 18 seconds locally and 23 seconds from MSX)

If you wish to test, my VM AG-PA-2012R2 (https://ag-pa-2012r2:3443/) has the template running on the appropriate host.

**Comment by bertysentry** [comment]
@alexdgilbert What about the many errors currently reported in **CollectionErrorCount**? Looks like many performance counters are not collecting.

**Comment by bertysentry** [comment]
@alexdgilbert and yes, please go ahead with your own alert thresholds on the performance counters :-)

**Review by bertysentry — APPROVED** [review]

**Comment by bertysentry** [comment]
@MohammedSentry @Raphyyyy Have you guys tested this?

**Review by Raphyyyy — APPROVED** [review]
Just loaded the Template and check the configuration .. and it looks good

image

**Pull request merged**
